name: SkyWarsReloaded
main: com.walrusone.skywars.SkyWarsReloaded
version: 2.5.4

depend: [Vault, Multiverse-Core, VoidWorld]

commands:
   swr:
      description: This is the main plugin command.
      usage: /<command> [args]
   global:
      aliases: [g]
      description: Allows you to send a message to all players
permissions:
  swr.*:
    description: Gives access to all swr commands
    children:
      swr.play: true
      swr.maps: true
      swr.signs: true
      swr.spectate: true
      swr.start: true
  swr.play:
    description: Gives access to the swr join and quit commands
    default: true
    children:
      swr.join: true
      swr.quit: true
      swr.kit: true
      swr.stats: true
  swr.admin:
    description: Gives access to the swr setspawn, list, games, endgame, and reload commands
    default: op
    children:
      swr.setspawn: true
      swr.list: true
      swr.games: true
      swr.endgame: true
      swr.reload: true
  swr.maps: 
    description: A.
    default: op
    children:
      swr.create: true
      swr.delete: true
      swr.edit: true
      swr.list: true
      swr.save: true
      swr.register: true
      swr.unregister: true
  swr.signs:
    description: Allows the user to create and destory swr signs.
    default: op
  swr.spectate:    
    description: Allows the user to spectate games.
    default: op
  swr.spectateshop:    
    description: Allows the user to use the spectator shop.
    default: op
  swr.opchest:    
    description: Allows the user to vote for OP chests.
    default: op
  swr.timevote:    
    description: Allows the user to vote for time of day on game start.
    default: op
  swr.jumpvote:    
    description: Allows the user to vote for jump boost on game start.
    default: op
  swr.start: 
    description: Allows the user to force start a game.
    default: op
  swr.global: 
    description: Allows the user to use global chat.
    default: op
  swr.vip:
    description: When a player has this permission, their score for kills and wins is given the vip multiplier in the config.
    default: op
  swr.color:
    description: Allows a player to use color chat.
    default: op
  swr.colorshop:
    description: Allows a player to use the color glass shop
    defualt: op
  swr.permkits:
    description: Allows a player to use the permanent kits shop
    default: op
  swr.join: 
    description: A.
    default: true
  swr.quit: 
    description: A.
    default: true
  swr.kit: 
    description: A.
    default: true
  swr.stats: 
    description: A.
    default: true
  swr.setspawn: 
    description: A.
    default: op
  swr.games: 
    description: A.
    default: op
  swr.list: 
    description: A.
    default: op
  swr.endgame: 
    description: A.
    default: op
  swr.reload: 
    description: A.
    default: op
  swr.create: 
    description: A.
    default: op
  swr.delete: 
    description: A.
    default: op
  swr.register: 
    description: A.
    default: op
  swr.unregister: 
    description: A.
    default: op
  swr.save: 
    description: A.
    default: op
  swr.edit: 
    description: A.
    default: op